TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  CROP_SIZE: 224
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/kinetics
  PATH_PREFIX: data/kinetics
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 24
  STEM_FUNC: x3d_stem
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [5], [11], [7]]
  SPATIAL_STRIDES: [[2], [2], [2], [2]]
X3D:
  EXPAND: 'M'
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 256
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
LOGS:
  DIR: logs/Kinetics/X3D_M
  PERIOD: 100
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
